name: "Linting workflow with flake8"
on: [push]
jobs: 
    lint:
        runs-on: ubuntu-latest
        container: python
        steps:
            - uses: actions/checkout@v4
            - name: "Prepare Python"
              run: "pip install flake8"
            - name: "Run linter"
              run: "flake8 autogaita --exclude=__init__.py --max-line-length 88 --ignore=E203"
